### PR TITLE
[WIP] new A/V API

### PR DESCRIPTION
**Pull request by zetok**
**Do not merge** yet.

currently only low-level binding is ~done. Safe interface is yet to be written.

Depends on https://github.com/irungentoo/toxcore/pull/1375.

I could make use of some feedback, and perhaps help - I'll see to writing safe interface, but given that I will be doing that for the first time, I don't know how well that will turn out `;)`

### CODE REVIEW

**Comment by quininer** [comment]
Any news about this?

**Comment by zetok** [comment]
> Any news about this?

I kinda have given up on doing it - sorry about that - limited time + knowledge about unsafe Rust is currently a bit of a showstopper.

Given limited time that I can spend on things, I think that rather than binding, I should put an effort to rewrite toxcore in pure Rust - I don't really have anything real as of yet, and it will take me at least months to rewrite toxcore in Rust.

As for this PR - low level (unsafe) binding to C is ~done, what is left is safe interface.

**Comment by quininer** [comment]
oh, I look forward to it. ;)

**Comment by quininer** [comment]
I try to finish it, now the audio is working. https://github.com/quininer/rstox/blob/newav/examples/testav.rs

**Comment by suhr** [comment]
(read the code a bit)
What happens when Tox is destroyed before ToxAV?

**Comment by quininer** [comment]
@suhr Probably will can't compile?

**Comment by suhr** [comment]
Well, ToxAV doesn't seem to be bound with Tox, so it should compile.

**Comment by zetok** [comment]
Well, it kinda works, and IMHO is sufficient for merge, given that current master's support for A/V is completely broken.

**Pull request merged**
