### PR TITLE
Fix toxcore API update for tox_new

### PR DESCRIPTION
**Pull request by quininer**
:)

### CODE REVIEW

**Comment by suhr** [comment]
Why does it need `&mut`?

**Comment by quininer** [comment]
@suhr 
No, actually only need `mut`..
I change.

**Comment by suhr** [comment]
Good. But I can't merge it while clients (qTox for example) doesn't support changed toxcore API.
So this PR remains open for a while.

**Comment by quininer** [comment]
qtox and other tox binding actually already support the `tox_new`. 

https://github.com/tux3/qTox/commit/6409b273a46dce821508293870e2a3ec897af07f
https://github.com/tox4j/tox4j/commit/98990c5341d69480cb8b791be8789325d7d37d48
https://github.com/lehitoskin/libtoxcore-racket/commit/08eed54631e0a2c1f8719e8e7c32bb7907fb87f7
https://github.com/Impyy/SharpTox/commit/26666d99b5016e8f0e4c8b188c5aedf3b4a49bf9
https://github.com/saneki/node-toxcore/commit/5237e483746453ee339aa0ccbb3b42f1f491d58d

**Pull request merged**
